### ISSUE TITLE
Migrate Give

### ISSUE THREAD

**Issue by Lepozepo** [NewSpring/Apollos#142]
## Acceptance Criteria

- [ ] A user should be able to "Give now"
- [ ] A user should be able to see their giving history
- [ ] A user can access their annual report
- [ ] A user can view their giving dashboard
- [ ] A user can see their giving history (Dashboard)
- [ ] A user can see their giving schedule (Dashboard)
- [ ] A user can manage their stored credit cards / bank accounts

## Context

Given a user needs to see their contributions or schedule contributions when they go to /give then they see a dashboard with recent activity, an interface to schedule contributions, and historical activity.
