### ISSUE TITLE
Giving: History

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#168]
## Acceptance Criteria

- [ ] It should show your contribution history
- [ ] It should allow you to filter your contribution history

## TODO:

- [ ] create some test contributions on their staging server and make sure any other acceptance critieria is flushed out
