### ISSUE TITLE
Groups: Group finder dashboard

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#169]
## Acceptance Criteria

- [x] It should have a form matching current app
- [ ] It should list relevant articles below
- [x] Tapping "Lets go" navigates to search results

## TODO:

@Lepozepo need to make sure data queries/mutation dependencies are either implemented or issues are created for them.
