### ISSUE TITLE
Search: Default search view

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#174]
## Acceptance Criteria

- [ ] It should show default search content before you type anything:
- [ ] Recommended by newspring
- [ ] Recently liked by others
- [ ] Input form at top to capture user input

## TODO:

- [ ] @Lepozepo need to make sure data queries/mutations are already built or issues are created to capture that work
