### ISSUE TITLE
Profile: dashboard

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#177]
## Acceptance Criteria

- [ ] It should show profile image at top, tapping on allows you to select an image
- [ ] It should have two tabs: likes and following
- [ ] It should list content for each tab

## TODO:

- [ ] @Lepozepo need to make sure data queries/mutations for this view are supported (or issues are created)

**Comment by Lepozepo** [comment]
I think `withUser`, `withProfileLikes` and `withProfileRecentLikes` are what's needed for this one. I'll double check.

**Comment by Lepozepo** [comment]
Checking on following, it may come from another subscribe function

**Comment by Lepozepo** [comment]
Yep, the `following` topics part is blocked by another subscription function that pushes changes to redux which is mapped into the component. Topics are attached directly onto the MongoDB user object, lol.

**Comment by Lepozepo** [comment]
The work pending on `following` I'm planning on attacking on #103
