### ISSUE TITLE
Profile: settings

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#178]
## Acceptance Criteria

- [ ] Build out settings menu accessed by clicking on cog icon inside of profile view
- [ ] Items in the settings menu should link out to individual forms (personal details, address, etc)

## TODO

- [ ] @Lepozepo need to make sure data queries/mutations for these views are supported (or issues are created)

**Comment by Lepozepo** [comment]
Mutations are pending
