### ISSUE TITLE
[EPIC] Initial Project Bootstrap

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#3]
## Acceptance Criteria

- [x] Initial file structure
- [x] Initial plan for low-level stack
- [x] Runnable on iOS, Android, Web
