### ISSUE TITLE
Analyze current state tree and identify TODO's and opportunities

### ISSUE THREAD

**Issue by Lepozepo** [NewSpring/Apollos#45]
## Acceptance Criteria

- [x] It should produce new issues
- [x] It should re-organize file structure
- [x] Have strategy for in place for handling state

**Comment by Lepozepo** [comment]
Account actions currently depend on `Meteor.methods`. To rewrite this we'll need Rock's API credentials:
- tokenName
- token
- baseURL

**Comment by Lepozepo** [comment]
This is what the tree looks like today for the most part:

```
accounts:
  account: true, // has an account
  authorized: false, // is logged in
  forgot: false, // ui state change (should move to component?)
  success: false, // form action result
  showWelcome: false, // show a welcome to your account message
  alternateAccounts: [], // used to let a user know they might have an account
  peopleWithoutAccountEmails: [
    // {
    //   email // String
    //   id // Number
    // }
  ],
  resettingAccount: false,
  hasPerson: false, // used to recommend account recovery to avoid duplicates

  person: {
    age: null, // Number
    birthdate: null, // Date
    campus: {
      name: null, // String
      shortcode: null, // String
    },
    email: null, // String
    home: {
      city: null, // String
      country: null, // String
      id: null, // Number
      zip: null, // String
      state: null, // String
      street1: null, // String
      street2: null, // String
    },
    firstName: null, // String
    lastName: null, // String
    nickName: null, // String
    phoneNumbers: [],
    photo: null, // String
  },

  data: {
    email: null, // String
    password: null, // String (encrypted before launch)
    terms: true, // String,
    firstName: null, // String
    lastName: null, // String
    personId: null, // Number
  },

  state: "default", // "submit", "loading", "signout"

  attempts: 0,
  errors: {
    // <id>: {
    //   message: "Email is required"
    // }
  },

audio:
  visibility: "dock", // "hide", "dock", "expand"
  order: "default", // "shuffle"
  repeat: "default", // "repeat", "repeat-one"
  progress: 0, // 0 - 100,
  time: "", // "4:34"
  seek: null,
  state: "default", // "playing", "paused", "loading", "ready"

  // array of tracks with index used to set order
  playlist: [
    // {
    //   title: null, // String
    //   duration: null, // String (mins:seconds)
    //   file: null // String (url)
    // }
  ],

  // currently playing album / parent + track
  playing: {
    // parent container of content
    album: {
      title: null, // String
      image: null, // String (url)
      blurredImage: null, // String (url)
      artist: null, // String
      id: null, // String (of a Number) // probably should convert
    },

    // currently playing track
    track: {
      title: null, // String
      duration: null, // String (mins:seconds)
      file: null, // String (url)
      artist: null, // String
    },

  },

give:
  userId: null, // used in native => web transactions

  step: 1, // Number (step along in progress bar to show)
  transactionType: "default", // "default", "guest", "recurring"
  url: "", // String representing the endpoint with NMI to submit to
  total: 0, // Number > 0 for allowing to move forward (calculated)
  state: "default", // "default", "loading", "submit", "error", "success"
  attempts: 0, // spam protection (auto calculated)
  reminderDate: null, // Date string for the next reminder

  errors: {
    // <id>: {
    //   message: "Card is declined"
    // }
  },

  savedAccount: {
    id: null, // Id of saved account to charge
    payment: {
      accountNumber: null, // accountNumber to be shown (full, not just last four)
      paymentType: null, // type of card
    },
    name: null, // name of card
  },

  accounts: {
    // <accountId>: Name
  },

  // transaction data
  transactions: {
    // <accountId>: Number // <accountId>: $ of gift
  },

  schedule: {
    start: null,  // Date (YYYYMMDD)
    // payments: null,  future feature for pledges
    frequency: null, // String of value from Rock
  },

  scheduleToRecover: null,
  recoverableSchedules: {

  },

  // form data
  data: {
    personal: {
      firstName: null, // String
      lastName: null, // String
      email: null, // String
      campus: null, // String
      campusId: null, // Number
    },
    billing: {
      streetAddress: null, // String
      streetAddress2: null, // String
      city: null, // String
      state: null, // String
      zip: null, // Number
      country: null, // String
    },
    payment: {
      name: null,
      type: "cc", // String ach or cc
      cardNumber: null, // Number
      expiration: null, // String
      ccv: null, // Number
      account: null, // String (for safety with international numbers)
      routing: null, // String (for safety with international numbers)
    },
  },

header:
  visible: true,
  statusBar: true,
  lockHolder: null,
  content: {
    title: "NewSpring",
    subTitle: "",
    color: brand,
    light: true,
    isSearch: false,
    showSettings: false,
    searchSubmit: false,
  },

liked:
  likes: [],

live:
  live: false,
  embedCode: null,
  show: true,
  float: false,

modal:
  visible: false,
  state: "default", // "full"
  content: null, // component to render within nav
  retrigger: null,
  props: {
    classes: [], // classes to be added to modal
    theme: false, // string of classes to overwrite theme
    styles: {}, // styles to be set on modal component
    keepNav: false,
    coverMiniPlayer: true,
    promptModal: false,
  },

nav:
  level: "TOP",
  visible: true,
  links: links.TOP,
  bgColor: "#202020",
  fgColor: "dark",

paging:
  page: 1,
  pageSize: 20,
  skip: 0,
  shouldUpdate: true,
  done: false,

responsive:
  width: null, // Number / screen width
  breakpoints: [], // array of stringified breakpoints
  _breakpoints: breakpoints, // object to test against

routing: // This is just a blackbox for history changes

search:
  term: null,
  items: [],
  page: 0,
  pageSize: 10,
  loading: false,
  done: false,
  none: false,
  searching: false,

sections:
  content: {}, // Items to be rendered in section modal
  props: {
    classes: [], // classes to be added to modal
    theme: false, // string of classes to overwrite theme
    styles: {}, // styles to be set on modal component
  },

share:
  sharing: false,
  content: {
    subject: null,
    text: null,
    activityTypes: null,
    image: null,
    url: null,
  },

topics:
  topics: [],
```

**Comment by Lepozepo** [comment]
### Suggested tree (partial)

```
## Suggested Tree

errors: [
  { type, message, id },
]

user:
  isLoggedIn:
  loginToken:
  email:

  profile:
    age: null, // Number
    birthdate: null, // Date
    campus: {
      name: null, // String
      shortcode: null, // String
    },
    home: {
      city: null, // String
      country: null, // String
      id: null, // Number
      zip: null, // String
      state: null, // String
      street1: null, // String
      street2: null, // String
    },
    firstName: null, // String
    lastName: null, // String
    nickName: null, // String
    phoneNumbers: [],
    photo: null, // String


mediaPlayer:
  visibility: "closed", // "closed", "docked", "expanded"
  order: "natural", // "shuffle", "natural"
  repeat: "no-repeat", // "repeat", "repeat-one", "no-repeat"

  // array of tracks with index used to set order
  playlist: [
    // {
    //   type: 'audio', // 'audio', 'video'
    //   title: null, // String
    //   subtitle: null, // String
    //   duration: null, // String (ms)
    //   url: null // String (url)
    //   placeholderImage: null, // String (url)
    //   id: 'asdf', // String
    // }
  ],

  // currently playing media
  current: String // id from playlist
  isPlaying: Bool
```

**Comment by Lepozepo** [comment]
## Suggested Tree (almost full proposal, just need to review user profiles)

### Common
```
errors: [
  { type, message, id },
]

header: // Remove it, this can be controlled from each page
nav: // Remove it, this can be controlled from each page
paging: // Remove it, this is too global, we should have this in a different place
responsive: // Remove it, this shouldn't change, currently hard-coded (less config is more)
routing: // Router's blackbox

user:
  isLoggedIn:
  loginToken:
  email:
  id:

  profile:
    age: null, // Number
    birthdate: null, // Date
    campus: {
      name: null, // String
      shortcode: null, // String
    },
    home: {
      city: null, // String
      country: null, // String
      id: null, // Number
      zip: null, // String
      state: null, // String
      street1: null, // String
      street2: null, // String
    },
    firstName: null, // String
    lastName: null, // String
    nickName: null, // String
    phoneNumbers: [],
    photo: null, // String

modal:
  isVisible: false,
  type: "popup", // "popup", "full"
  content: null, // component to render (Form, Message)
  contentProps: {}, // component props

mediaPlayer:
  visibility: "closed", // "closed", "docked", "expanded"
  order: "natural", // "shuffle", "natural"
  repeat: "no-repeat", // "repeat", "repeat-one", "no-repeat"

  // array of tracks with index used to set order
  playlist: [
    // {
    //   type: 'audio', // 'audio', 'video'
    //   title: null, // String
    //   subtitle: null, // String
    //   duration: null, // String (ms)
    //   url: null // String (url)
    //   placeholderImage: null, // String (url)
    //   id: 'asdf', // String
    // }
  ],

  // currently playing media
  current: String // id from playlist
  isPlaying: Bool
```

### Features
```
homeFeed: // Is new
  scrollPosition, // Maybe
  page: Number,
  pageSize: Number,
  isLoading: Bool,
  isLoadingMore: Bool,
  content: [ // content blocks of [article, music, sermon, devotionals, etc]
    { // ContentBlock
      id: String
      hasLike: Bool
      title: String
      type: String // oneOf article, music, sermon, devotionals, etc * see categories.icon.js, the icon is inferred by the component's "channel"
    }
  ],

sections: // This is a static menu
  scrollPosition, // Maybe
  sections: [
    {
      linkTo: String
      title: String
      imageUrl: String
      subsections: [
        {
          title: String
          imageUrl: String
          linkTo: String
        }
      ]
    }
  ]

sectionsFeeds: // Is new, current app tracks the view selected from sections via the modal. We could also bring this into sections since they are related
  [type]: // where type is oneOf article, sermon, music, devotionals, etc
    scrollPosition, // Maybe
    page: Number,
    pageSize: Number,
    isLoading: Bool,
    isLoadingMore: Bool,
    content: [ // content blocks of [article, music, sermon, devotionals, etc]
      { // ContentBlock
        id: String
        hasLike: Bool
        title: String
        type: String // oneOf article, music, sermon, devotionals, etc * see categories.icon.js, the icon is inferred by the component's "channel"
      }
    ],

give:
  step: 1, // Number (step along in progress bar to show)
  transactionType: "default", // "default", "guest", "recurring"
  url: "", // String representing the endpoint with NMI to submit to
  total: 0, // Number > 0 for allowing to move forward (calculated)
  state: "default", // "default", "loading", "submit", "error", "success"
  attempts: 0, // spam protection (auto calculated)
  reminderDate: null, // Date string for the next reminder

  savedAccount: {
    id: null, // Id of saved account to charge
    payment: {
      accountNumber: null, // accountNumber to be shown (full, not just last four)
      paymentType: null, // type of card
    },
    name: null, // name of card
  },

  accounts: {
    // <accountId>: Name
  },

  // transaction data
  transactions: {
    // <accountId>: Number // <accountId>: $ of gift
  },

  schedule: {
    start: null,  // Date (YYYYMMDD)
    // payments: null,  future feature for pledges
    frequency: null, // String of value from Rock
  },

  scheduleToRecover: null,
  recoverableSchedules: {

  },

  // form data
  form: {
    personal: {
      firstName: null, // String
      lastName: null, // String
      email: null, // String
      campus: null, // String
      campusId: null, // Number
    },
    billing: {
      streetAddress: null, // String
      streetAddress2: null, // String
      city: null, // String
      state: null, // String
      zip: null, // Number
      country: null, // String
    },
    payment: {
      name: null,
      type: "cc", // String ach or cc
      cardNumber: null, // Number
      expiration: null, // String
      ccv: null, // Number
      account: null, // String (for safety with international numbers)
      routing: null, // String (for safety with international numbers)
    },
  },


live: // Live sermon? Not too sure how this works yet
  live: false,
  embedCode: null,
  show: true,
  float: false,

groupFinder: // Is new, is currently handled loosely through apollo
  form:
    groupTags: [String]
    campus: String
    zip: String
    searchCriteria: String
  filters: [String]
  page: Number,
  pageSize: Number,
  isLoading: Bool,
  isLoadingMore: Bool,
  results: [
    {
      id: String
      title: String
      date: Date
      location: { latitude, longitude },
      description: String,
      tags: [String]
      leaders: [{ imageUrl, firstName, lastName }]
      members: [{ imageUrl }]
      campus: String
      information: String
    }
  ]
  relatedContent: [
    { // ContentBlock
      id: String
      hasLike: Bool
      title: String
      type: String // oneOf article, music, sermon, devotionals, etc * see categories.icon.js, the icon is inferred by the component's "channel"
    }
  ]

search:
  searchCriteria: String
  page: Number,
  pageSize: Number,
  isLoading: Bool,
  isLoadingMore: Bool,
  results: [
    { // Can be content blocks or groups from group finder
      id: String
      url: String
      title: String
      description: String
      imageUrl: String
    }
  ]

share: // Remove it, this is just a function in a component

topics:
  topics: [],
```

**Comment by Lepozepo** [comment]
## Suggested Tree (Final Proposal)

### Common
```
errors: [
  { type, message, id },
]

header: // Remove it, this can be controlled from each page
nav: // Remove it, this can be controlled from each page
paging: // Remove it, this is too global, we should have this in a different place
responsive: // Remove it, this shouldn't change, currently hard-coded (less config is more)
routing: // Router's blackbox

user:
  isLoggedIn:
  loginToken:
  email:
  id:

  profile:
    age: null, // Number
    birthdate: null, // Date
    campus: {
      name: null, // String
      shortcode: null, // String
    },
    home: {
      city: null, // String
      country: null, // String
      id: null, // Number
      zip: null, // String
      state: null, // String
      street1: null, // String
      street2: null, // String
    },
    firstName: null, // String
    lastName: null, // String
    nickName: null, // String
    phoneNumbers: [],
    photo: null, // String

modal:
  isVisible: false,
  type: "popup", // "popup", "full"
  content: null, // component to render (Form, Message)
  contentProps: {}, // component props

mediaPlayer:
  visibility: "closed", // "closed", "docked", "expanded"
  order: "natural", // "shuffle", "natural"
  repeat: "no-repeat", // "repeat", "repeat-one", "no-repeat"

  // array of tracks with index used to set order
  playlist: [
    // {
    //   type: 'audio', // 'audio', 'video'
    //   title: null, // String
    //   subtitle: null, // String
    //   duration: null, // String (ms)
    //   url: null // String (url)
    //   placeholderImage: null, // String (url)
    //   id: 'asdf', // String
    // }
  ],

  // currently playing media
  current: String // id from playlist
  isPlaying: Bool
```

### Features
```
homeFeed: // Is new
  scrollPosition, // Maybe
  page: Number,
  pageSize: Number,
  isLoading: Bool,
  isLoadingMore: Bool,
  following: [] // replaces topics
  content: [ // content blocks of [article, music, sermon, devotionals, etc]
    { // ContentBlock
      id: String
      hasLike: Bool
      title: String
      type: String // oneOf article, music, sermon, devotionals, etc * see categories.icon.js, the icon is inferred by the component's "channel"
    }
  ],

sections: // This is a static menu
  scrollPosition, // Maybe
  sections: [
    {
      linkTo: String
      title: String
      imageUrl: String
      subsections: [
        {
          title: String
          imageUrl: String
          linkTo: String
        }
      ]
    }
  ]

sectionsFeeds: // Is new, current app tracks the view selected from sections via the modal. We could also bring this into sections since they are related
  [type]: // where type is oneOf article, sermon, music, devotionals, etc
    scrollPosition, // Maybe
    page: Number,
    pageSize: Number,
    isLoading: Bool,
    isLoadingMore: Bool,
    content: [ // content blocks of [article, music, sermon, devotionals, etc]
      { // ContentBlock
        id: String
        hasLike: Bool
        title: String
        type: String // oneOf article, music, sermon, devotionals, etc * see categories.icon.js, the icon is inferred by the component's "channel"
      }
    ],

give:
  step: 1, // Number (step along in progress bar to show)
  transactionType: "default", // "default", "guest", "recurring"
  url: "", // String representing the endpoint with NMI to submit to
  total: 0, // Number > 0 for allowing to move forward (calculated)
  state: "default", // "default", "loading", "submit", "error", "success"
  attempts: 0, // spam protection (auto calculated)
  reminderDate: null, // Date string for the next reminder

  savedAccount: {
    id: null, // Id of saved account to charge
    payment: {
      accountNumber: null, // accountNumber to be shown (full, not just last four)
      paymentType: null, // type of card
    },
    name: null, // name of card
  },

  accounts: {
    // <accountId>: Name
  },

  // transaction data
  transactions: {
    // <accountId>: Number // <accountId>: $ of gift
  },

  schedule: {
    start: null,  // Date (YYYYMMDD)
    // payments: null,  future feature for pledges
    frequency: null, // String of value from Rock
  },

  scheduleToRecover: null,
  recoverableSchedules: {

  },

  // form data
  form: {
    personal: {
      firstName: null, // String
      lastName: null, // String
      email: null, // String
      campus: null, // String
      campusId: null, // Number
    },
    billing: {
      streetAddress: null, // String
      streetAddress2: null, // String
      city: null, // String
      state: null, // String
      zip: null, // Number
      country: null, // String
    },
    payment: {
      name: null,
      type: "cc", // String ach or cc
      cardNumber: null, // Number
      expiration: null, // String
      ccv: null, // Number
      account: null, // String (for safety with international numbers)
      routing: null, // String (for safety with international numbers)
    },
  },


live: // Live sermon? Not too sure how this works yet
  live: false,
  embedCode: null,
  show: true,
  float: false,

groupFinder: // Is new, is currently handled loosely through apollo
  form:
    groupTags: [String]
    campus: String
    zip: String
    searchCriteria: String
  filters: [String]
  page: Number,
  pageSize: Number,
  isLoading: Bool,
  isLoadingMore: Bool,
  results: [
    {
      id: String
      title: String
      date: Date
      location: { latitude, longitude },
      description: String,
      tags: [String]
      leaders: [{ imageUrl, firstName, lastName }]
      members: [{ imageUrl }]
      campus: String
      information: String
    }
  ]
  relatedContent: [
    { // ContentBlock
      id: String
      hasLike: Bool
      title: String
      type: String // oneOf article, music, sermon, devotionals, etc * see categories.icon.js, the icon is inferred by the component's "channel"
    }
  ]

search:
  searchCriteria: String
  page: Number,
  pageSize: Number,
  isLoading: Bool,
  isLoadingMore: Bool,
  results: [
    { // Can be content blocks or groups from group finder
      id: String
      url: String
      title: String
      description: String
      imageUrl: String
    }
  ]

share: // Remove it, this is just a function in a component

topics: // Remove it, this is to know what they're following for their home feed
```

**Comment by Lepozepo** [comment]
## Suggested Tree (reviewed)

### Common
```
errors: [
  { type, message, id },
]

header: // Remove it, this can be controlled from each page
nav: // Remove it, this can be controlled from each page
paging: // Remove it, this is too global, we should have this in a different place
responsive: // Remove it, this shouldn't change, currently hard-coded (less config is more)

routing: // Router's blackbox

user:
  isLoggedIn:
  loginToken:
  email:
  id:
  following: [] // replaces topics

  profile:
    age: null, // Number
    birthdate: null, // Date
    campus: {
      name: null, // String
      shortcode: null, // String
    },
    home: {
      city: null, // String
      country: null, // String
      id: null, // Number
      zip: null, // String
      state: null, // String
      street1: null, // String
      street2: null, // String
    },
    firstName: null, // String
    lastName: null, // String
    nickName: null, // String
    phoneNumbers: [],
    photo: null, // String

modal: // Remove it
  isVisible: false,
  type: "popup", // "popup", "full"
  content: null, // component to render (Form, Message)
  contentProps: {}, // component props

mediaPlayer:
  visibility: "closed", // "closed", "docked", "expanded"
  order: "natural", // "shuffle", "natural"
  repeat: "no-repeat", // "repeat", "repeat-one", "no-repeat"

  // array of tracks with index used to set order
  playlist: [
    // {
    //   type: 'audio', // 'audio', 'video'
    //   title: null, // String
    //   subtitle: null, // String
    //   duration: null, // String (ms)
    //   url: null // String (url)
    //   placeholderImage: null, // String (url)
    //   id: 'asdf', // String
    // }
  ],

  // currently playing media
  current: String // id from playlist
  isPlaying: Bool
  seekProgress: Number (ms)
```

### Features
```
homeFeed: // Is new
  scrollPosition, // Maybe
  page: Number,
  pageSize: Number,
  isLoading: Bool,
  isLoadingMore: Bool,
  content: [ // content blocks of [article, music, sermon, devotionals, etc]
    { // ContentBlock
      id: String
      hasLike: Bool
      title: String
      imageUrl: String
      channel: String // oneOf article, music, sermon, devotionals, etc * see categories.icon.js, the icon is inferred by the component's "channel"
    }
  ],

sections: // This is a static menu
  scrollPosition, // Maybe
  sections: [
    {
      linkTo: String
      title: String
      imageUrl: String
      subsections: [
        {
          title: String
          imageUrl: String
          linkTo: String
        }
      ]
    }
  ]

sectionsFeeds: // Is new, current app tracks the view selected from sections via the modal. We could also bring this into sections since they are related
  [type]: // where type is oneOf article, sermon, music, devotionals, etc
    scrollPosition, // Maybe
    page: Number,
    pageSize: Number,
    isLoading: Bool,
    isLoadingMore: Bool,
    content: [ // content blocks of [article, music, sermon, devotionals, etc]
      { // ContentBlock
        id: String
        hasLike: Bool
        title: String
        imageUrl: String
        channel: String // oneOf article, music, sermon, devotionals, etc * see categories.icon.js, the icon is inferred by the component's "channel"
      }
    ],

give:
  step: 1, // Number (step along in progress bar to show)
  transactionType: "default", // "default", "guest", "recurring"
  url: "", // String representing the endpoint with NMI to submit to
  total: 0, // Number > 0 for allowing to move forward (calculated)
  state: "default", // "default", "loading", "submit", "error", "success"
  attempts: 0, // spam protection (auto calculated)
  reminderDate: null, // Date string for the next reminder

  savedAccount: {
    id: null, // Id of saved account to charge
    payment: {
      accountNumber: null, // accountNumber to be shown (full, not just last four)
      paymentType: null, // type of card
    },
    name: null, // name of card
  },

  accounts: {
    // <accountId>: Name
  },

  // transaction data
  transactions: {
    // <accountId>: Number // <accountId>: $ of gift
  },

  schedule: {
    start: null,  // Date (YYYYMMDD)
    // payments: null,  future feature for pledges
    frequency: null, // String of value from Rock
  },

  scheduleToRecover: null,
  recoverableSchedules: {

  },

  // form data
  form: {
    personal: {
      firstName: null, // String
      lastName: null, // String
      email: null, // String
      campus: null, // String
      campusId: null, // Number
    },
    billing: {
      streetAddress: null, // String
      streetAddress2: null, // String
      city: null, // String
      state: null, // String
      zip: null, // Number
      country: null, // String
    },
    payment: {
      name: null,
      type: "cc", // String ach or cc
      cardNumber: null, // Number
      expiration: null, // String
      ccv: null, // Number
      account: null, // String (for safety with international numbers)
      routing: null, // String (for safety with international numbers)
    },
  },

live:
  live: false,
  embedCode: null,
  show: true,
  float: false,

groupFinder: // Is new, is currently handled loosely through apollo
  form:
    groupTags: [String]
    campus: String
    zip: String
    searchCriteria: String
  filters: [String]
  page: Number,
  pageSize: Number,
  isLoading: Bool,
  isLoadingMore: Bool,
  results: [
    {
      id: String
      title: String
      date: Date
      location: { latitude, longitude },
      description: String,
      tags: [String]
      leaders: [{ imageUrl, firstName, lastName }]
      members: [{ imageUrl }]
      campus: String
      information: String
    }
  ]
  relatedContent: [
    { // ContentBlock
      id: String
      hasLike: Bool
      title: String
      imageUrl: String
      channel: String // oneOf article, music, sermon, devotionals, etc * see categories.icon.js, the icon is inferred by the component's "channel"
    }
  ]

search:
  searchCriteria: String
  page: Number,
  pageSize: Number,
  isLoading: Bool,
  isLoadingMore: Bool,
  results: [
    { // Can be content blocks or groups from group finder
      id: String
      url: String
      title: String
      description: String
      imageUrl: String
    }
  ]

share: // Remove it, this is just a function in a component

topics: // Remove it, this is to know what they're following for their home feed
```
