### ISSUE TITLE
[EPIC] Navigation

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#48]
## Acceptance Criteria

- [ ] User can navigate to the different tabs
- [ ] User can navigate to an interior page
- [ ] User can open up a modal
