### ISSUE TITLE
[EPIC] Accounts

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#60]
## Acceptance Criteria

- [ ] User can login
- [ ] User can signup
- [ ] User can logout
- [ ] User can complete forgot password flow
