### ISSUE TITLE
[EPIC] Giving

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#61]
## Acceptance Criteria

- [ ] A user should be able to "Give now"
- [ ] A user should be able to see their giving history
- [ ] A user can access their annual report
- [ ] A user can view their giving dashboard
- [ ] A user can see their giving history (Dashboard)
- [ ] A user can see their giving schedule (Dashboard)
- [ ] A user can manage their stored credit cards / bank accounts

**Comment by Lepozepo** [comment]
Messed up and duplicated the issue at #142
