### ISSUE TITLE
[EPIC] Series / Sermons

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#62]
## Acceptance Criteria

- [x] A user can browse series
- [x] A user can view an individual series
- [ ] User can watch a series trailer / media
- [ ] A user can watch previous series videos / media / sermons
