### ISSUE TITLE
[EPIC] Studies / Devotionals

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#64]
## Acceptance Criteria

- [ ] User can view list in sections
- [ ] User can read individual an individual study
- [ ] User can see list of devotionals in study
- [ ] User can open / read individual devotional inside of a study
- [ ] User can swipe between devotional and scripture
