### ISSUE TITLE
[EPIC] Music

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#66]
## Acceptance Criteria

- [ ] User can view list of albums (in sections)
- [ ] User can view an album, see individual tracks
- [ ] User can play an album, with basic playlist controls
- [ ] User can access sub-menu for a track - view album, share
