### ISSUE TITLE
[EPIC] Group Finder

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#70]
## Acceptance Criteria

- [ ] I can find groups
- [ ] I can contact the group leader (bounces to website)
- [ ] I can view info about a group and who's in it
