### ISSUE TITLE
[EPIC] User Profile

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#72]
## Acceptance Criteria

- [ ] See likes
- [ ] See following / edit
- [ ] Edit profile photo
- [ ] Edit profile data - personal details, address, password, etc
- [ ] Give feedback
- [ ] See saved payment accounts, scheduled contributions, etc
- [ ] Privacy Policy
- [ ] Terms of Use
