### ISSUE TITLE
[EPIC] Notifications

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#75]
## TODO

- [ ] Define existing notification strategy that's in the app
- [ ] Identify third party provider for notification delivery

----

## Acceptance Criteria

- [ ] Support notification delivery that's maps to what's currently available
- [ ] Make sure migration structure - people that used to receive notifications - will be handled after upgrading
- [ ] Prompt user to receive notifications
- [ ] Provide place to disable notifications
