### ISSUE TITLE
[EPIC] Error capturing / reporting

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#76]
## Acceptance Criteria

- [ ] Runtime errors should be dispatched to analytics service, such as bugsnag
- [ ] Audit our error handling, are we confident in it?
- [ ] Investigate new React functionality like https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html

**Comment by conrad-vanl** [comment]
Fixed in #300
