### ISSUE TITLE
[EPIC] Media Playing

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#79]
## Acceptance Criteria

- [ ] Should have a universal audio player with basic playlist support
- [ ] should have a standard video player, that pauses audio when playing
- [ ] User has basic play controls: shuffle, repeat, next, back, play, pause, etc.

**Comment by conrad-vanl** [comment]
@burkeshartsis when you get a chance, can you add issues to this (and maybe tweak the acceptance criteria) to encompass what needs to be done still with audio / video stuff?

(This is just encompassing the players and the persistent player at the bottom of the screen - the music browser in content is a separate epic #66)

**Comment by IsaacHardy** [comment]
@conrad-vanl @burkeshartsis What are we planning on doing with these [EPIC] github issues?

**Comment by conrad-vanl** [comment]
They're just buckets to connect other issues to. They should be checked off and closed. They were used to initially organize and estimate work from our initial engagement brief.

I can work on that.

**Comment by IsaacHardy** [comment]
@conrad-vanl That's great!
